Add final-status check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,7 +27,7 @@ jobs:
           cd Android/MMKV
           ./gradlew build
 
-  android:
+  android-test:
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -57,3 +57,20 @@ jobs:
           arch: ${{ matrix.arch }}
           working-directory: ./Android/MMKV
           script: ./gradlew connectedCheck
+
+  # Status check that is required in branch protection rules.
+  final-status:
+    needs:
+      - build
+      - android-test
+    runs-on: ubuntu-slim
+    if: always()
+    steps:
+      - name: Check
+        run: |
+          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
+          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
+            echo "One or more required jobs failed"
+            exit 1
+          fi
+          echo "All required jobs completed successfully."
